include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
